import {v4 as uuid} from "uuid"

export const products = [
  {
    _id: uuid(),
    name: 'iPhone 13 Pro',
    description: 'The latest flagship iPhone with advanced features.',
    price: 1099,
    stockUnits: 15,
    image: "https://www.apple.com/v/iphone-se/j/images/overview/shared-compare/compare_iphone_14__eeblt4putp26_medium_2x.jpg",
    category: 'Smartphones',
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: 'MacBook Pro',
    description: 'Powerful laptop for professional users.',
    price: 1999,
    stockUnits: 20,
    image: 'https://www.apple.com/v/macbook-air/o/images/overview/hero_mba_m1__mfge6fbp7t2m_medium_2x.jpg',
    category: 'Laptops',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'HP Spectre x360',
    description: 'Convertible laptop with excellent performance.',
    price: 1299,
    stockUnits: 12,
    image: 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08347244.png',
    category: 'Laptops',
    rating: 4.3,
  },
  {
    _id: uuid(),
    name: 'Samsung Galaxy S21 Ultra',
    description: 'Feature-packed Android smartphone.',
    price: 1199,
    stockUnits: 18,
    image: 'https://cdn.dxomark.com/wp-content/uploads/medias/post-76697/galaxys21_ultra.jpg',
    category: 'Smartphones',
    rating: 3,
  },
  {
    _id: uuid(),
    name: 'Dell XPS 15',
    description: 'High-performance laptop with a stunning display.',
    price: 1799,
    stockUnits: 8,
    image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9520/media-gallery/black/laptop-xps-9520-t-black-gallery-5.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=676&qlt=100,1&resMode=sharp2&size=676,402&chrss=full',
    category: 'Laptops',
    rating: 4.4,
  },
  {
    _id: uuid(),
    name: 'Google Pixel 6 Pro',
    description: 'Flagship Google smartphone with excellent camera capabilities.',
    price: 999,
    stockUnits: 10,
    image: 'https://lh3.googleusercontent.com/q-pHCr8EekvezKd7jIWmglzCQ4LNZ5grFOKV_4CADEQtXU63a7OBiHbSlIu2oeYXvjo5lHyuBlsLvSLQdv6-cP1_U0lmqgv-9ng=rw-e365-w2880',
    category: 'Smartphones',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'Lenovo ThinkPad X1',
    description: 'Ultra-portable business laptop with premium features.',
    price: 1499,
    stockUnits: 5,
    image: 'https://p4-ofp.static.pub/fes/cms/2023/02/10/7qjkk7h1a53t8jq5snivyzumxw040v193587.png',
    category: 'Laptops',
    rating: 4.1,
  },
  {
    _id: uuid(),
    name: 'Sony PlayStation 5',
    description: 'Next-generation gaming console with powerful hardware.',
    price: 499,
    stockUnits: 25,
    image: 'https://gmedia.playstation.com/is/image/SIEPDC/playstation-5-horizontal-product-shot-01-ps5-en-23nov20?$1200px--t$',
    category: 'Gaming Consoles',
    rating: 4.9,
  },
  {
    _id: uuid(),
    name: 'Samsung QLED Q90R',
    description: 'High-end 4K QLED TV with excellent picture quality.',
    price: 2299,
    stockUnits: 3,
    image: 'https://image-us.samsung.com/SamsungUS/home/televisions-and-home-theater/tvs/qled-tvs/pdp/qn65q90rafxza/gallery/QN75Q90RAFXZA_001_Front1_Silver_NS_01.jpg?$product-details-jpg$',
    category: 'Other',
    rating: 4.6,
  },
  {
    _id: uuid(),
    name: 'Amazon Echo (4th Gen)',
    description: 'Smart speaker with Alexa voice assistant.',
    price: 99,
    stockUnits: 30,
    image: 'https://m.media-amazon.com/images/I/61NIsUGl+FL.jpg',
    category: 'Others',
    rating: 4.3,
  },
  {
    _id: uuid(),
    name: 'GoPro HERO9 Black',
    description: 'Action camera for capturing high-quality footage.',
    price: 449,
    stockUnits: 6,
    image: 'https://static.gopro.com/assets/blta2b8522e5372af40/blt99e8a5176eb6f095/643ec27767e76213aa9ba281/pdp-h9-image01-1024-2x.png?width=1920&quality=80&auto=webp&disable=upscale',
    category: 'Cameras',
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: 'LG CX OLED TV',
    description: 'Premium OLED TV with exceptional picture quality.',
    price: 1999,
    stockUnits: 4,
    image: 'https://www.lg.com/us/images/tvs/md07501258/gallery/desktop-01.jpg',
    category: 'Others',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'Microsoft Surface Pro 7',
    description: 'Versatile 2-in-1 laptop for productivity on the go.',
    price: 899,
    stockUnits: 14,
    image: 'https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/MSFT_Surface_Go_3_in_Laptop_Mode_RWFKxc:VP5-1920x1080?fmt=png-alpha',
    category: 'Laptops',
    rating: 4.2,
  },
  {
    _id: uuid(),
    name: 'Ipad',
    description: 'Macbooks power, tablets convenience. all in one device',
    price: 999,
    stockUnits: 14,
    image: 'https://www.apple.com/v/ipad/home/cf/images/overview/compare_ipad_pro__erf9x8mw04sy_large_2x.png',
    category: 'Tablets',
    rating: 4.4,
  },
];
