import {v4 as uuid} from "uuid"

export const products = [
  {
    _id: uuid(),
    name: 'iPhone 13 Pro',
    description: 'The latest flagship iPhone with advanced features.',
    price: 1099,
    stockUnits: 15,
    image: 'iphone13pro.png',
    category: 'Smartphones',
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: 'MacBook Pro',
    description: 'Powerful laptop for professional users.',
    price: 1999,
    stockUnits: 20,
    image: 'macbookpro.png',
    category: 'Laptops',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'HP Spectre x360',
    description: 'Convertible laptop with excellent performance.',
    price: 1299,
    stockUnits: 12,
    image: 'hpspectre.png',
    category: 'Laptops',
    rating: 4.3,
  },
  {
    _id: uuid(),
    name: 'Samsung Galaxy S21 Ultra',
    description: 'Feature-packed Android smartphone.',
    price: 1199,
    stockUnits: 18,
    image: 's21ultra.png',
    category: 'Smartphones',
    rating: 3,
  },
  {
    _id: uuid(),
    name: 'Dell XPS 15',
    description: 'High-performance laptop with a stunning display.',
    price: 1799,
    stockUnits: 8,
    image: 'dellxps15.png',
    category: 'Laptops',
    rating: 4.4,
  },
  {
    _id: uuid(),
    name: 'Google Pixel 6 Pro',
    description: 'Flagship Google smartphone with excellent camera capabilities.',
    price: 999,
    stockUnits: 10,
    image: 'pixel6pro.png',
    category: 'Smartphones',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'Lenovo ThinkPad X1 Carbon',
    description: 'Ultra-portable business laptop with premium features.',
    price: 1499,
    stockUnits: 5,
    image: 'thinkpadx1.png',
    category: 'Laptops',
    rating: 4.1,
  },
  {
    _id: uuid(),
    name: 'Sony PlayStation 5',
    description: 'Next-generation gaming console with powerful hardware.',
    price: 499,
    stockUnits: 25,
    image: 'ps5.png',
    category: 'Gaming Consoles',
    rating: 4.9,
  },
  {
    _id: uuid(),
    name: 'Samsung QLED Q90R',
    description: 'High-end 4K QLED TV with excellent picture quality.',
    price: 2299,
    stockUnits: 3,
    image: 'samsungq90r.png',
    category: 'Other',
    rating: 4.6,
  },
  {
    _id: uuid(),
    name: 'Amazon Echo (4th Gen)',
    description: 'Smart speaker with Alexa voice assistant.',
    price: 99,
    stockUnits: 30,
    image: 'amazonecho.png',
    category: 'Others',
    rating: 4.3,
  },
  {
    _id: uuid(),
    name: 'GoPro HERO9 Black',
    description: 'Action camera for capturing high-quality footage.',
    price: 449,
    stockUnits: 6,
    image: 'goprohero9.png',
    category: 'Cameras',
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: 'LG CX OLED TV',
    description: 'Premium OLED TV with exceptional picture quality.',
    price: 1999,
    stockUnits: 4,
    image: 'lgcxoled.png',
    category: 'Others',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'Microsoft Surface Pro 7',
    description: 'Versatile 2-in-1 laptop for productivity on the go.',
    price: 899,
    stockUnits: 14,
    image: 'surfacepro7.png',
    category: 'Laptops',
    rating: 4.2,
  },
  {
    _id: uuid(),
    name: 'Ipad',
    description: 'Macbooks power, tablets convenience. all in one device',
    price: 999,
    stockUnits: 14,
    image: 'ipad.png',
    category: 'Tablets',
    rating: 4.4,
  },
];
